config/routes.rb
Rails.application.routes.draw do
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"

  resources :users, except: [:new]
  get 'register', to: 'users#new'
  get 'search', to: 'users#search'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Defines all the path for articles
  resources :articles

  resources :categories

end

app/models/article.rb
class Article < ApplicationRecord
    #un articolo può appartenere ad un solo user
    belongs_to :user

    has_many :article_categories
    has_many :categories, through: :article_categories

    validates :title, presence: true, length: {minimum: 5, maximum: 100}
    validates :description, presence: true, length: {minimum: 5, maximum: 1000}
end
  

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    #prima di eseguire i metodi indicati dentro le [] eseguirà :set_article rendendo @article disponibile dentro i metodi senza cosi dover ripetere
    #"@article = Article.find(params[:id])" in tutti i metodi (DRY-> DONT REPEAT YOURSELF)"
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def show
        #binding.breakp -> blocca il codice e fa partire il debug, scrivo params in console per vedere i parametri
        #@article = Article.find(params[:id])
    end

    def index
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end

    #mostra il form per creare un nuovo articolo
    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:notice] = "Articolo salvato!"
            redirect_to article_path(@article)
        else
            #flash[:alert] = "Articolo non salvato!"
            render 'new', status: :unprocessable_entity
        
        end
    end


    def edit
      #@article = Article.find(params[:id])
    end

    def update
        #@article = Article.find(params[:id])
        puts params
        if @article.update(article_params)
            flash[:notice] = "Articolo modificato!"
            redirect_to article_path(@article)
        else
            #flash[:alert] = "Articolo non modificato!"
            render 'edit', status: :unprocessable_entity
        end
    end

    def destroy
        #@article = Article.find(params[:id])
        if @article.destroy 
            flash[:notice] = "Articolo rimosso!"
            redirect_to articles_path
        end
    end

    private #sotto sono metodi privati

    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description)
    end

    def require_same_user
        if current_user !=  @article.user && !current_user.admin?
          flash[:alert] = "Azione non autorizzata, puoi modificare o cancellare solo i tuoi articoli."  
          redirect_to article_path(@article)
        end
    end

end

app/views/articles/_articles.html.erb
<div class="">
    <div class="row">
          <% @articles.each do |article| %>
            <div class="col-sm-6 p-3 my-3"> 
              <div class="card shadow-lg">
                  <div class="d-flex p-3 gap-3">
                       <%=render 'shared/categories', obj: article%>
                        <div class="ms-auto">
                          <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2" />
                        </div>
                        <div class="pb-2">
                          <%= link_to user_path(article.user.id), class: "text-decoration-none" do %>
                            <strong class="text-dark"><%= article.user.username %></strong>
                          <% end %>
                        </div>
                  </div>
               
                <%= link_to article_path(article.id), class: "text-decoration-none text-dark" do %>
                  <div class="card-body">
                    <h5 class="card-title"><%= article.title %></h5>
                    <p class="card-text"><%= article.description.truncate(100, separator: ' ') %></p>

                    <div class="d-flex align-items-baseline justify-content-end gap-1">
                      <h6 class="card-text"><small class="text-muted">Creato <%= time_ago_in_words(article.created_at)%></small> | </h6>
                      <h6 class="card-text"><small class="text-muted">Ultimo aggiornamento <%= time_ago_in_words(article.updated_at) %></small></h6>
                    </div>
                  </div>
                <% end %>

              </div>
            </div>
          <% end %>
      </div>
</div>

app/views/articles/_form.html.erb
<%=render 'shared/errors', obj: @article%>
<%=form_with(model: @article, local: true ) do |f|%>
 <div class="container shadow-lg p-5 my-5 bg-body rounded-3">
    <h3><b>Titolo</b></h3>
    <p>
     <!--<%= f.label :title%><br>-->
      <%= f.text_field :title, class: "w-100 p-1"%>
    </p>

    <h3><b>Descrizione</b></h3>
       
     <p>
        <!--<%= f.label :description%><br>-->
       <%= f.text_area :description, class: "w-100 p-1"%>
     </p>

     <h3><b>Categorie</b></h3>
       
     <p>
        <!--<%= f.label :description%><br>-->
       <%= f.collection_select :category_ids, Category.all, :id, :name, 
           {prompt: "Scegli le varie categorie"}, {multiple: true, size: 3, class: "form-select"} %>

     </p>


    <p>
      <%= f.submit "Salva", class: "btn btn-warning" %>
    </p> 
  </div>
<%end %>

app/views/articles/edit.html.erb
<div class="container pt-5 mt-3">
<h1>Gestione articolo</h1>
<!--prende la pagina con nome _form.hmtl.erb-->
<%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div class="p-5 vh-100">
<%= render 'articles' %>
</div>
<div class="apple_pagination">
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<div class="container pt-5 mt-3">
<h1>Crea un nuovo articolo</h1>
<%= render 'form' %>
</div>

app/views/articles/show.html.erb
<br>
 <div class="container shadow-lg p-5 my-3 bg-body rounded-3">
        <div class="d-flex align-items-center gap-3 mb-1">
            <%if logged_in? && (@article.user == current_user || current_user.admin? ) %>
                <div class="pb-2">
                    <%= link_to edit_article_path(@article.id) do %>
                        <img width="20" height="20" src="<%= image_path('svg/pencil-square.svg') %>" alt="Your Blog">
                    <% end %>
                </div>
                <div class="pb-2">
                    <%= link_to article_path(@article.id), data: { turbo_method: :delete, turbo_confirm: 'Sei sicuro di voler cancellare l\'articolo?' } do %>
                        <img width="20" height="20" src="<%= image_path('svg/trash3-fill.svg') %>" alt="Your Blog">
                    <% end %>
                </div>
            <% end %>

            <%=render 'shared/categories', obj: @article%>
        
            <div class="p-2 ms-auto">    
                <div class="d-flex">
                    <div>
                     <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2" />
                    </div>
                    <div class="pb-2">  
                      <%= link_to user_path(@article.user.id), class: "text-decoration-none" do %>
                         <strong class="text-dark"><%= @article.user.username %></strong>
                       <% end %>
                    </div>
                </div>
            </div>
        </div>

    <h3><b>Titolo</b></h3>
    <p>
        <%= @article.title%>
    </p>

    <h3><b>Descrizione</b></h3>
    <p>
       <%=  simple_format(@article.description)%>
    </p>

    

    
<div class="d-flex justify-content-end mt-5" >
  <div class="p-2">
     <small class="text-muted">Creato <%= time_ago_in_words(@article.created_at)%></small> |
     <small class="text-muted"> Ultimo aggiornamento <%= time_ago_in_words(@article.updated_at) %></small>
  </div>
</div>


 </div>


 <div class="container shadow-lg p-5 my-5 bg-body rounded-3">
    <h3 class="mb-3"><b>Gestione commenti</b></h3>
    <div class="list-group">
        <a href="#" class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
            <img src="https://github.com/twbs.png" alt="twbs" width="32" height="32" class="rounded-circle flex-shrink-0">
            <div class="d-flex gap-2 w-100 justify-content-between">
                <div>
                    <h6 class="mb-0">Marco Rossi</h6>
                    <p class="mb-0 opacity-75">Articolo fantastico, rispecchia la realtà</p>
                </div>
                <small class="opacity-50 text-nowrap">now</small>
            </div>
        </a>
        <a href="#" class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
            <img src="https://github.com/twbs.png" alt="twbs" width="32" height="32" class="rounded-circle flex-shrink-0">
            <div class="d-flex gap-2 w-100 justify-content-between">
                <div>
                    <h6 class="mb-0">Giulia Marzi</h6>
                    <p class="mb-0 opacity-75">Fantastico! pensavo fosse più difficile</p>
                </div>
                <small class="opacity-50 text-nowrap">now</small>
            </div>
        </a>
        <a href="#" class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
            <img src="https://github.com/twbs.png" alt="twbs" width="32" height="32" class="rounded-circle flex-shrink-0">
            <div class="d-flex gap-2 w-100 justify-content-between">
                <div>
                    <h6 class="mb-0">Luca Zefferi</h6>
                    <p class="mb-0 opacity-75">Tutto sommato semplice da realizzare, grazie.</p>
                </div>
                <small class="opacity-50 text-nowrap">1w</small>
            </div>
        </a>
    </div>
 </div>