config/routes.rb
Rails.application.routes.draw do
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"

  resources :users, except: [:new]
  get 'register', to: 'users#new'
  get 'search', to: 'users#search'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Defines all the path for articles
  resources :articles

  resources :categories

end

app/models/user.rb
class User < ApplicationRecord

    #prima di salvare l'email la fa diventare downcase
    before_save { self.email = email.downcase }

    #un utente può avere più articoli
    has_many :articles, dependent: :destroy #dependent: :destroy se cancello l'utente anche tutti gli articoli verranno cancellati

    #uniqueness: true -> rende unico lo username di default tiene conto delle maiuscole e minuscole quindi ("Luca" e "luca" per lui sono due string differenti)
    validates :username, uniqueness: true, 
                         presence: true, length: {minimum: 3, maximum: 25}

    VALID_EMAIL_REGEX= /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i
    #uniqueness: { case_sensitive: false} -> rende unico l'email e non tiene conto delle maiuscole e minuscole quindi ("Luca" e "luca" per lui sono due string uguali)
    validates :email, uniqueness: { case_sensitive: false},
                      presence: true, length: { maximum: 100},
                      format:{with:VALID_EMAIL_REGEX,multiline:true}

    has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    #prima di eseguire i metodi indicati dentro le [] eseguirà :set_user rendendo @user disponibile dentro i metodi senza cosi dover ripetere
    #"@User = User.find(params[:id])" in tutti i metodi (DRY-> DONT REPEAT YOURSELF)"
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index, :create, :new, :search]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def new
        @user = User.new
    end

    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end

    def show
        @articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end

    def create
        @user = User.new(user_params)
    
        if @user.save
            session[:user_id] = @user.id #serve per far accedere automaticamente l'utente appena si è registrato
            flash[:notice] = "Benvenuto a bordo!"
            redirect_to root_path
        else
            #flash[:alert] = "Articolo non salvato!"
            render 'new', status: :unprocessable_entity
        end
    end


    
    def edit
        #@user = User.find(params[:id])
    end
  
      def update
          #@user = User.find(params[:id])
          puts params
          if @user.update(user_params)
              flash[:notice] = "Profilo modificato!"
              redirect_to user_path(@user.id)
          else
              #flash[:alert] = "Profilo non modificato!"
              render 'edit', status: :unprocessable_entity
          end
      end
  
      def destroy
          #@user = User.find(params[:id])
          if @user.destroy 
             UserMailer.goodbye_email(@user).deliver_now
              flash[:notice] = "Il profilo e tutti gli articoli associati sono stati elimanti!"
              if current_user == @user
              session[:user_id] = nil
              redirect_to root_path
              end
          end
      end

      
    def search
        @users = User.where('username LIKE ?', "%#{params[:query]}%").limit(5)
        render json: @users
    end

    private

    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def require_same_user
        #se l'utente loggato non è l'utente di cui sta provando ad eliminare l'account e non è nemmeno un admin allora vieta l'azione
        if current_user !=  @user && !current_user.admin?
          flash[:alert] = "Azione non autorizzata, puoi modificare o cancellare solo il tuo profilo."  
          redirect_to user_path(@user)
        end
    end


end

app/views/users/_form.html.erb
<div class="container col-xl-10 col-xxl-8 px-4 py-5 vh-100">
  <%=render 'shared/errors', obj: @user%>
    <div class="row align-items-center g-lg-5 py-5">
      <div class="col-lg-7 text-center text-lg-start">
        <h1 class="display-4 fw-bold lh-1 mb-3 text-warning">Registrati </h1>
        <p class="col-lg-10 fs-4 mb-3 ">
            Ciao e benvenuto nel nostro sito web! Siamo entusiasti di averti qui. 
            Registrati per esplorare un mondo ricco di opportunità che ti aspetta. 
            Qui, ogni giorno è un’occasione per scoprire qualcosa di nuovo. 
            Non vediamo l’ora di vedere cosa hai da dire!
        </p>
      </div>
      <div class="col-md-10 mx-auto col-lg-5">
        <%=form_with(model: @user, local: true ) do |f|%>
    
            <% if @user.new_record? %> 
            <h3 class="fw-normal">Inserisci i dati per registrati</h1>
            <%else%>
            <h3 class="fw-normal">Modica i dati del tuo profilo</h1>
            <%end %>

            <div class="form-floating">
                <%= f.text_field :username, class: "form-control", placeholder: "Username"%>
                <label for="floatingUsername">Username</label>
            </div>
          <div class="form-floating">
            <%= f.email_field :email, class: "form-control", placeholder: "Email"%>
            <label for="floatingEmail">Email</label>
          </div>
          <div class="form-floating">
            <%= f.password_field :password, class: "form-control", placeholder: "Password"%>
            <label for="floatingPassword">Password</label>
          </div>
          
          <%= f.submit(@user.new_record? ? "Registrati" : "Salva", class: "w-100 btn btn-lg btn-primary mt-3 rounded-pill")%>
          <% if !logged_in? %>
          <div class="mt-2 mt-2 text-center">
                <%= link_to 'Accedi', login_path, class: "text-decoration-none "%>
          </div>
          <%end %>
          <p class="mt-5 mb-3 text-muted">© 2024</p>
      <%end %>
        <small class="text-muted">Cliccando registrati, accetti i termini di uso.</small>
      </div>
    </div>
  </div>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<div class="p-5">
    <div class="row">
        <% @users.each do |user| %>
        <div class="col-sm-6 p-3 my-3">
            
            <div class="card shadow-lg">
                <div class="d-flex align-items-center">
                <%if logged_in? && current_user.admin? %>
                    <div class="p-3">
                        <%= link_to user_path(user.id), data: { turbo_method: :delete, turbo_confirm: 'Sei sicuro di voler eliminare il profilo?' } do %>
                            <img width="20" height="20" src="<%= image_path('svg/trash3-fill.svg') %>" alt="Your Blog">
                        <% end %>
                    </div>
                <% end %>
                    <%= link_to user_path(user.id), class: "text-decoration-none ms-auto" do %>
                        <div class="d-flex align-items-center p-3">
                            <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2" />
                            <div class="pb-2">
                                <strong class="text-dark"><%= user.username %></strong>
                            </div>
                        </div>
                    <% end %>
                </div>
                       
                <div class="card-body">
                    <h5 class="card-title"><%= user.username %></h5>
                    <p class="card-text"><%= user.email %></p>
                    <br>
                    <div class="d-flex justify-content-end">
                        <h6 class="card-text"><small class="text-muted">Creato <%= time_ago_in_words(user.created_at)%> fa</small></h6>
                    </div>
                </div>
            </div>
        </div>
        <% end %>
    </div>
</div>
<div class="apple_pagination">
    <div class="page_info">
      <%= page_entries_info @users %>
    </div>
    <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<br />

<div class="container">
    <%if logged_in? && @user == current_user %>
    <h3>Gestione profilo</h3>
    <% else %>
    <h3><%= @user.username %></h3>
    <% end %>

    <div class="shadow-lg p-5 my-3 bg-body rounded-3">
        <div class="d-flex gap-3">
            <%if logged_in? && @user == current_user %>
            <div class="pb-2">
                <%= link_to edit_user_path(@user.id) do %>
                <img width="20" height="20" src="<%= image_path('svg/pencil-square.svg') %>" alt="Your Blog" />
                <% end %>
            </div>
            <% end %>

            <%if logged_in? && (@user == current_user || current_user.admin?)%>
            <div class="pb-2 me-3">
                <%= link_to user_path(@user.id), data: { turbo_method: :delete, turbo_confirm: 'Sei sicuro di voler eliminare il profilo?' } do %>
                <img width="20" height="20" src="<%= image_path('svg/trash3-fill.svg') %>" alt="Your Blog" />
                <% end %>
            </div>
            <% end %>
        </div>
        <div class="d-flex align-items-center gap-3 mb-1">
            <div class="pb-2 flex-column me-2">
                <div><strong>Username</strong></div>
                <div><%= @user.username %></div>
            </div>
            <%if logged_in? && (@user == current_user || current_user.admin?) %>
            <div class="pb-2 flex-column">
                <div><strong>Email</strong></div>
                <div><%= @user.email %></div>
            </div>
            <% end %>
            <div class="pb-2 flex-column">
                <div><strong>Articoli</strong></div>
                <div><%= @user.articles.count %></div>
            </div>

            <div class="ms-auto p-2 d-flex">
                <a href="#" class="d-flex align-items-center link-dark text-decoration-none" id="userReference" data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2" />
                </a>
                <strong><span><%= @user.username %> </span></strong>
            </div>
        </div>
        <%if logged_in? && (@user == current_user) %>
            <%= link_to new_article_path, class: "fw-bold text-decoration-none text-dark" do %>
            <div class="d-flex gap-2 mt-3">
                <img class="d-block mb-4" src="<%= image_path('svg/plus-circle.svg') %>" alt="" width="30" height="30" />
                Nuovo articolo
            </div>
            <% end %>
        <% end %>
    </div>
    <%= render 'articles/articles' %>
</div>

<div class="apple_pagination">
    <div class="page_info">
        <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @articles, :container => false %>
</div>