config/routes.rb
Rails.application.routes.draw do
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"

  resources :users, except: [:new]
  get 'register', to: 'users#new'
  get 'search', to: 'users#search'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Defines all the path for articles
  resources :articles

  resources :categories

end

app/models/category.rb
class Category < ApplicationRecord

    #uniqueness: { case_sensitive: false} -> rende unico l'email e non tiene conto delle maiuscole e minuscole quindi ("Sport" e "sport" per lui sono due string uguali)
    validates :name, presence: true, uniqueness: { case_sensitive: false}, length: {minimum: 5, maximum: 100}

    has_many :article_categories
    has_many :articles, through: :article_categories

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    #prima di eseguire i metodi indicati dentro le [] eseguirà :set_article rendendo @article disponibile dentro i metodi senza cosi dover ripetere
    #"@article = Article.find(params[:id])" in tutti i metodi (DRY-> DONT REPEAT YOURSELF)"
    before_action :set_category, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_admin, only: [:edit, :update, :destroy]

    def show
        #binding.breakp -> blocca il codice e fa partire il debug, scrivo params in console per vedere i parametri
        #@article = Article.find(params[:id])
    end

    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end

    #mostra il form per creare un nuovo articolo
    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Categoria salvata!"
            redirect_to category_path(@category)
        else
            #flash[:alert] = "Articolo non salvato!"
            render 'new', status: :unprocessable_entity
        
        end
    end


    def edit
      #@article = Article.find(params[:id])
    end

    def update
        #@article = Article.find(params[:id])
        puts params
        if @category.update(category_params)
            flash[:notice] = "Categoria modificata!"
            redirect_to category_path(@category)
        else
            #flash[:alert] = "Articolo non modificato!"
            render 'edit', status: :unprocessable_entity
        end
    end

    def destroy
        #@article = Article.find(params[:id])
        if @category.destroy 
            flash[:notice] = "Categoria rimossa!"
            redirect_to category_path
        end
    end

    private #sotto sono metodi privati

    def set_category
        @category = Category.find(params[:id])
    end

    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !current_user.admin?
            flash[:alert] = "Azione non autorizzata, non puoi modificare le categorie."  
            redirect_to root_path
          end
    end

end

app/views/categories/_form.html.erb
<%=render 'shared/errors', obj: @category%>
<%=form_with(model: @category, local: true ) do |f|%>
 <div class="container shadow-lg p-5 my-5 bg-body rounded-3">
    <h3><b>Nome categoria</b></h3>
    <p>
     <!--<%= f.label :title%><br>-->
      <%= f.text_field :name, class: "w-100 p-1"%>
    </p>
    <p>
      <%= f.submit "Salva", class: "btn btn-warning" %>
    </p> 
  </div>
<%end %>

app/views/categories/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<div class="p-5 vh-100">

    <h1>Visita le varie categorie</h1>
    
    <%if logged_in? && current_user.admin? %>
        <%= link_to new_category_path, class: "fw-bold text-decoration-none text-dark" do %>
            <div class="d-flex gap-2 mt-3">
                <img class="d-block mb-4" src="<%= image_path('svg/plus-circle.svg') %>" alt="" width="30" height="30" />
                    Nuovo categoria
                </div>
        <% end %>
    <% end %>

    <div class="row">
        <% @categories.each do |category| %>
        <div class="col-sm-4 p-3 my-3">
            
            <div class="card shadow-lg">
                <div class="d-flex align-items-center">

                    <%= link_to category_path(category.id), class: "text-decoration-none" do %>
                        <div class="p-3">
                            <div class="pb-2">
                                <strong class="text-dark"><%= category.name %></strong>
                            </div>
                        </div>
                    <% end %>

                    <%if logged_in? && current_user.admin? %>
                    <div class="ms-auto d-flex">
                        <div class="p-3">
                            <%= link_to category_path(category.id), data: { turbo_method: :delete, turbo_confirm: 'Sei sicuro di voler eliminare la categoria?' } do %>
                                <img width="20" height="20" src="<%= image_path('svg/trash3-fill.svg') %>" alt="Cancella categoria">
                            <% end %>
                        </div>
                        <div class="p-3">
                            <%= link_to edit_category_path(category.id) do %>
                            <img width="20" height="20" src="<%= image_path('svg/pencil-square.svg') %>" alt="Modifica categoria" />
                            <% end %>
                        </div>
                    </div>
                    <% end %>
                    
                </div>
                    
            </div>
        </div>
        <% end %>
    </div>
</div>
<div class="apple_pagination">
    <div class="page_info">
      <%= page_entries_info @users %>
    </div>
    <%= will_paginate @users, :container => false %>
</div>

app/views/categories/new.html.erb
<h1>New</h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<div class="p-5 vh-100">
   <div class="">
        <div class="row">
           <% @category.articles.paginate(page: params[:page], per_page: 10).each do |article| %>
                <div class="col-sm-6 p-3 my-3"> 
                <div class="card shadow-lg">
                    <div class="d-flex p-3 gap-3">
                        <%=render 'shared/categories', obj: article%>
                            <div class="ms-auto">
                            <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2" />
                            </div>
                            <div class="pb-2">
                            <%= link_to user_path(article.user.id), class: "text-decoration-none" do %>
                                <strong class="text-dark"><%= article.user.username %></strong>
                            <% end %>
                            </div>
                    </div>
                
                    <%= link_to article_path(article.id), class: "text-decoration-none text-dark" do %>
                    <div class="card-body">
                        <h5 class="card-title"><%= article.title %></h5>
                        <p class="card-text"><%= article.description.truncate(100, separator: ' ') %></p>

                        <div class="d-flex align-items-baseline justify-content-end gap-1">
                        <h6 class="card-text"><small class="text-muted">Creato <%= time_ago_in_words(article.created_at)%></small> | </h6>
                        <h6 class="card-text"><small class="text-muted">Ultimo aggiornamento <%= time_ago_in_words(article.updated_at) %></small></h6>
                        </div>
                    </div>
                    <% end %>

                </div>
                </div>
            <% end %>
        </div>
    </div>
</div>