config/routes.rb
Rails.application.routes.draw do
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"

  resources :users, except: [:new]
  get 'register', to: 'users#new'
  get 'search', to: 'users#search'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Defines all the path for articles
  resources :articles

  resources :categories

end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <p class="col-md-4 mb-0 text-body-secondary">© 2024 Company, Inc</p>

    <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
    </a>

    <ul class="nav col-md-4 justify-content-end">
      <li class="nav-item mb-2"><%= link_to 'Home', root_path, class: "nav-link px-2 text-body-secondary"%></li>
      <li class="nav-item mb-2"><%= link_to 'Popolari', articles_path, class: "nav-link px-2 text-body-secondary"%></li>
      <li class="nav-item mb-2"> <%= link_to 'Blogger', users_path, class: "nav-link px-2 text-body-secondary"%></li>
    </ul>
  </footer>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top bg-light">
      <div class="container-fluid">
        <!--<a href="/" class="navbar-brand">
          <img width="34" height="34" src="<%= image_path('svg/logo.svg') %>" alt="Your Blog">
        </a>-->

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to 'BlogCreator', root_path, class: "nav-link active fw-bold"%>
            </li>
            <li class="nav-item">
              <%= link_to 'Blogger', users_path, class: "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to 'Popolari', articles_path, class: "nav-link"%>
            </li>

            <li class="nav-item">
              <%= link_to 'Categorie', categories_path, class: "nav-link"%>
            </li>

             <% if logged_in?%>
             <li class="nav-item">
              <%= link_to (current_user.admin? ? 'Profilo (Admin)' : 'Profilo'), user_path(current_user.id), class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Esci', logout_path , class: "nav-link", data: { turbo_method: :delete } %>
              </li>
             <%end%>
          </ul>
          <div class="ms-auto">
              <input autocomplete="off" class="form-control me-2" type="search" id="searchUser" placeholder="Cerca blogger" aria-label="Search">
              <ul class="list-group position-absolute" id="user-list">
              </ul>
          <div>
       <div>
      </div>
    </nav>

<script>

      $('#searchUser').on('keyup', function() {
        var query = $(this).val();
        if (query.length <= 2) {
        return;
        }
        $.ajax({
          url: '/search',
          method: 'GET',
          data: {query: $(this).val()},
          dataType: 'json',
          success: function(data) {
              $('#user-list').empty();
              data.forEach(function(user) {
                var link = $('<a>').attr('href', '/users/' + user.id).addClass('nav-link').text(user.username);
                var listItem = $('<li>').addClass("list-group-item").append(link);
                $('#user-list').append(listItem);
              });
          }
      });
    });

    $('#searchUser').on('focusout', function() {
       setTimeout(() => { 
       $('#user-list').empty();
        }, 100);
    });

</script>

app/views/layouts/_messages.html.erb
<%flash.each do |name, msg|%>
   <div class="container mt-4 alert alert-success alert-dismissible fade show" role="alert">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-circle-fill" viewBox="0 0 16 16">
      <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0m-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
      </svg>
      <%=msg%>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
   </div>    
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="mt-5 pt-2 fadeIn">
    <%= render 'layouts/messages' %>
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>